import { createContext, useContext } from 'react';
import {
  BASE_KPI, MONTHLY_DATA, QUARTER_FINANCE, GAUGES,
  CATEGORY_DATA, DONUT_COLORS, TOP_PRODUCTS,
  INVENTORY_SUMMARY, STOCK_ALERTS, SALES_CHANNELS,
  CUSTOMER_STATS, CUSTOMER_DONUT, EXPENSE_CARDS,
  MARKETING_STATS, CAMPAIGNS,
} from '../data/sampleData';

export const SAMPLE_CONTEXT = {
  BASE_KPI, MONTHLY_DATA, QUARTER_FINANCE, GAUGES,
  CATEGORY_DATA, DONUT_COLORS, TOP_PRODUCTS,
  INVENTORY_SUMMARY, STOCK_ALERTS, SALES_CHANNELS,
  CUSTOMER_STATS, CUSTOMER_DONUT, EXPENSE_CARDS,
  MARKETING_STATS, CAMPAIGNS,
};

export const DataContext = createContext(SAMPLE_CONTEXT);
export const useData = () => useContext(DataContext);
